[2022-02-11 22:00:02,213] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow_for_email.test_function scheduled__2022-02-11T21:00:00+00:00 [queued]>
[2022-02-11 22:00:02,287] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow_for_email.test_function scheduled__2022-02-11T21:00:00+00:00 [queued]>
[2022-02-11 22:00:02,289] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 22:00:02,291] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-11 22:00:02,293] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-11 22:00:02,366] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-11 21:00:00+00:00
[2022-02-11 22:00:02,379] {standard_task_runner.py:52} INFO - Started process 19876 to run task
[2022-02-11 22:00:02,394] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow_for_email', 'test_function', 'scheduled__2022-02-11T21:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow_for_email.py', '--cfg-path', '/tmp/tmpp_wykxot', '--error-file', '/tmp/tmp5y9_kcpn']
[2022-02-11 22:00:02,397] {standard_task_runner.py:77} INFO - Job 101: Subtask test_function
[2022-02-11 22:00:02,651] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow_for_email.test_function scheduled__2022-02-11T21:00:00+00:00 [running]> on host c762f4aacf84
[2022-02-11 22:00:02,848] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=dhapathekabolchi@gmail.com
AIRFLOW_CTX_DAG_OWNER=arflow
AIRFLOW_CTX_DAG_ID=test_workflow_for_email
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T21:00:00+00:00
[2022-02-11 22:00:02,854] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_workflow_for_email.py", line 9, in test_function
    with io.open("/opt/airflow/output_files1/tutorial2.txt","w",encoding="utf-8")as f1:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_files1/tutorial2.txt'
[2022-02-11 22:00:02,904] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=test_workflow_for_email, task_id=test_function, execution_date=20220211T210000, start_date=20220211T220002, end_date=20220211T220002
[2022-02-11 22:00:02,988] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:02,991] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:02,995] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:02,997] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:02,999] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,002] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,006] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,008] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,011] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,013] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,015] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,017] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-11 22:00:03,073] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-02-11 22:00:03,078] {email.py:208} INFO - Email alerting: attempt 1
[2022-02-11 22:00:05,210] {email.py:220} INFO - Sent an alert email to ['dhapathekabolchi@gmail.com']
[2022-02-11 22:00:07,480] {standard_task_runner.py:92} ERROR - Failed to execute job 101 for task test_function
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_workflow_for_email.py", line 9, in test_function
    with io.open("/opt/airflow/output_files1/tutorial2.txt","w",encoding="utf-8")as f1:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_files1/tutorial2.txt'
[2022-02-11 22:00:07,519] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-11 22:00:07,653] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
