[2022-02-07 17:27:35,202] {processor.py:163} INFO - Started process (PID=655) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:35,207] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:27:35,211] {logging_mixin.py:109} INFO - [2022-02-07 17:27:35,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:35,230] {logging_mixin.py:109} INFO - [2022-02-07 17:27:35,224] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DA
          ^
SyntaxError: invalid syntax
[2022-02-07 17:27:35,301] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:35,336] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.141 seconds
[2022-02-07 17:27:36,358] {processor.py:163} INFO - Started process (PID=657) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:36,362] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:27:36,365] {logging_mixin.py:109} INFO - [2022-02-07 17:27:36,365] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:36,385] {logging_mixin.py:109} INFO - [2022-02-07 17:27:36,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG
           ^
SyntaxError: invalid syntax
[2022-02-07 17:27:36,418] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:36,438] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.086 seconds
[2022-02-07 17:27:41,665] {processor.py:163} INFO - Started process (PID=661) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:41,669] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:27:41,676] {logging_mixin.py:109} INFO - [2022-02-07 17:27:41,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:41,699] {logging_mixin.py:109} INFO - [2022-02-07 17:27:41,696] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-02-07 17:27:41,759] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:41,816] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.157 seconds
[2022-02-07 17:27:46,659] {processor.py:163} INFO - Started process (PID=676) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:46,673] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:27:46,680] {logging_mixin.py:109} INFO - [2022-02-07 17:27:46,680] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:46,780] {logging_mixin.py:109} INFO - [2022-02-07 17:27:46,759] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-02-07 17:27:46,851] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:46,878] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.230 seconds
[2022-02-07 17:27:48,004] {processor.py:163} INFO - Started process (PID=679) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:48,010] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:27:48,014] {logging_mixin.py:109} INFO - [2022-02-07 17:27:48,013] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:48,033] {logging_mixin.py:109} INFO - [2022-02-07 17:27:48,031] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(da)
               ^
SyntaxError: invalid syntax
[2022-02-07 17:27:48,087] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:27:48,127] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.131 seconds
[2022-02-07 17:28:05,035] {processor.py:163} INFO - Started process (PID=709) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:05,038] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:05,040] {logging_mixin.py:109} INFO - [2022-02-07 17:28:05,040] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:05,054] {logging_mixin.py:109} INFO - [2022-02-07 17:28:05,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag)
                ^
SyntaxError: invalid syntax
[2022-02-07 17:28:05,088] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:05,110] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.083 seconds
[2022-02-07 17:28:07,165] {processor.py:163} INFO - Started process (PID=713) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:07,171] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:07,174] {logging_mixin.py:109} INFO - [2022-02-07 17:28:07,174] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:07,195] {logging_mixin.py:109} INFO - [2022-02-07 17:28:07,193] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="")
                      ^
SyntaxError: invalid syntax
[2022-02-07 17:28:07,242] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:07,261] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.104 seconds
[2022-02-07 17:28:10,326] {processor.py:163} INFO - Started process (PID=716) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:10,328] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:10,331] {logging_mixin.py:109} INFO - [2022-02-07 17:28:10,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:10,348] {logging_mixin.py:109} INFO - [2022-02-07 17:28:10,347] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="test")
                          ^
SyntaxError: invalid syntax
[2022-02-07 17:28:10,377] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:10,391] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.071 seconds
[2022-02-07 17:28:13,616] {processor.py:163} INFO - Started process (PID=721) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:13,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:13,622] {logging_mixin.py:109} INFO - [2022-02-07 17:28:13,621] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:13,639] {logging_mixin.py:109} INFO - [2022-02-07 17:28:13,637] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="test_workflow")
                                   ^
SyntaxError: invalid syntax
[2022-02-07 17:28:13,689] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:13,713] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.105 seconds
[2022-02-07 17:28:43,135] {processor.py:163} INFO - Started process (PID=772) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:43,138] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:43,140] {logging_mixin.py:109} INFO - [2022-02-07 17:28:43,140] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:43,154] {logging_mixin.py:109} INFO - [2022-02-07 17:28:43,152] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="test_workflow",)
                                    ^
SyntaxError: invalid syntax
[2022-02-07 17:28:43,186] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:43,204] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.073 seconds
[2022-02-07 17:28:50,100] {processor.py:163} INFO - Started process (PID=796) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:50,103] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:50,107] {logging_mixin.py:109} INFO - [2022-02-07 17:28:50,106] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:50,125] {logging_mixin.py:109} INFO - [2022-02-07 17:28:50,123] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="test_workflow",st)
                                      ^
SyntaxError: invalid syntax
[2022-02-07 17:28:50,180] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:50,206] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.112 seconds
[2022-02-07 17:28:52,266] {processor.py:163} INFO - Started process (PID=798) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:52,281] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:52,284] {logging_mixin.py:109} INFO - [2022-02-07 17:28:52,283] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:52,299] {logging_mixin.py:109} INFO - [2022-02-07 17:28:52,297] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 5
    with DAG(dag_id="test_workflow",start_date=)
                                               ^
SyntaxError: invalid syntax
[2022-02-07 17:28:52,340] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:52,359] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.098 seconds
[2022-02-07 17:28:54,422] {processor.py:163} INFO - Started process (PID=800) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:54,427] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:54,429] {logging_mixin.py:109} INFO - [2022-02-07 17:28:54,429] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:54,445] {logging_mixin.py:109} INFO - [2022-02-07 17:28:54,443] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=)
                                               ^
SyntaxError: invalid syntax
[2022-02-07 17:28:54,477] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:54,496] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.095 seconds
[2022-02-07 17:28:57,613] {processor.py:163} INFO - Started process (PID=805) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:57,616] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:57,618] {logging_mixin.py:109} INFO - [2022-02-07 17:28:57,618] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:57,630] {logging_mixin.py:109} INFO - [2022-02-07 17:28:57,629] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 2
    from da
          ^
SyntaxError: invalid syntax
[2022-02-07 17:28:57,672] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:57,693] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.085 seconds
[2022-02-07 17:28:59,219] {processor.py:163} INFO - Started process (PID=807) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:59,223] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:28:59,227] {logging_mixin.py:109} INFO - [2022-02-07 17:28:59,227] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:59,252] {logging_mixin.py:109} INFO - [2022-02-07 17:28:59,250] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 2
    from dat
           ^
SyntaxError: invalid syntax
[2022-02-07 17:28:59,300] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:28:59,329] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.117 seconds
[2022-02-07 17:29:01,392] {processor.py:163} INFO - Started process (PID=817) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:01,395] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:01,397] {logging_mixin.py:109} INFO - [2022-02-07 17:29:01,396] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:01,418] {logging_mixin.py:109} INFO - [2022-02-07 17:29:01,417] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 2
    from datet
             ^
SyntaxError: invalid syntax
[2022-02-07 17:29:01,459] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:01,499] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.111 seconds
[2022-02-07 17:29:05,268] {processor.py:163} INFO - Started process (PID=824) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:05,272] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:05,274] {logging_mixin.py:109} INFO - [2022-02-07 17:29:05,274] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:05,289] {logging_mixin.py:109} INFO - [2022-02-07 17:29:05,287] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=)
                                               ^
SyntaxError: invalid syntax
[2022-02-07 17:29:05,326] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:05,354] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.092 seconds
[2022-02-07 17:29:07,280] {processor.py:163} INFO - Started process (PID=825) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:07,282] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:07,285] {logging_mixin.py:109} INFO - [2022-02-07 17:29:07,285] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:07,298] {logging_mixin.py:109} INFO - [2022-02-07 17:29:07,296] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=)
                                               ^
SyntaxError: invalid syntax
[2022-02-07 17:29:07,325] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:07,345] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.070 seconds
[2022-02-07 17:29:09,457] {processor.py:163} INFO - Started process (PID=828) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:09,476] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:09,478] {logging_mixin.py:109} INFO - [2022-02-07 17:29:09,477] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:09,491] {logging_mixin.py:109} INFO - [2022-02-07 17:29:09,490] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=da)
                                                 ^
SyntaxError: invalid syntax
[2022-02-07 17:29:09,520] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:09,535] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.083 seconds
[2022-02-07 17:29:11,589] {processor.py:163} INFO - Started process (PID=830) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:11,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:11,593] {logging_mixin.py:109} INFO - [2022-02-07 17:29:11,593] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:11,606] {logging_mixin.py:109} INFO - [2022-02-07 17:29:11,605] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime())
                                                         ^
SyntaxError: invalid syntax
[2022-02-07 17:29:11,634] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:11,650] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.067 seconds
[2022-02-07 17:29:16,885] {processor.py:163} INFO - Started process (PID=854) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:16,892] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:16,896] {logging_mixin.py:109} INFO - [2022-02-07 17:29:16,896] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:16,921] {logging_mixin.py:109} INFO - [2022-02-07 17:29:16,917] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,))
                                                              ^
SyntaxError: invalid syntax
[2022-02-07 17:29:16,962] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:16,984] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.117 seconds
[2022-02-07 17:29:20,500] {processor.py:163} INFO - Started process (PID=860) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:20,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:20,507] {logging_mixin.py:109} INFO - [2022-02-07 17:29:20,507] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:20,523] {logging_mixin.py:109} INFO - [2022-02-07 17:29:20,522] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7))
                                                                 ^
SyntaxError: invalid syntax
[2022-02-07 17:29:20,564] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:20,589] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.097 seconds
[2022-02-07 17:29:30,077] {processor.py:163} INFO - Started process (PID=868) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:30,082] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:30,085] {logging_mixin.py:109} INFO - [2022-02-07 17:29:30,085] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:30,104] {logging_mixin.py:109} INFO - [2022-02-07 17:29:30,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),sc)
                                                                    ^
SyntaxError: invalid syntax
[2022-02-07 17:29:30,202] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:30,244] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.173 seconds
[2022-02-07 17:29:31,612] {processor.py:163} INFO - Started process (PID=878) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:31,617] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:31,619] {logging_mixin.py:109} INFO - [2022-02-07 17:29:31,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:31,634] {logging_mixin.py:109} INFO - [2022-02-07 17:29:31,633] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval=)
                                                                                    ^
SyntaxError: invalid syntax
[2022-02-07 17:29:31,666] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:31,683] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.077 seconds
[2022-02-07 17:29:32,662] {processor.py:163} INFO - Started process (PID=879) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:32,668] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:32,680] {logging_mixin.py:109} INFO - [2022-02-07 17:29:32,677] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:32,697] {logging_mixin.py:109} INFO - [2022-02-07 17:29:32,695] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="")
                                                                                      ^
SyntaxError: invalid syntax
[2022-02-07 17:29:32,757] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:32,783] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.142 seconds
[2022-02-07 17:29:35,809] {processor.py:163} INFO - Started process (PID=884) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:35,813] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:35,817] {logging_mixin.py:109} INFO - [2022-02-07 17:29:35,816] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:35,837] {logging_mixin.py:109} INFO - [2022-02-07 17:29:35,835] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily")
                                                                                            ^
SyntaxError: invalid syntax
[2022-02-07 17:29:35,869] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:35,886] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.089 seconds
[2022-02-07 17:29:37,789] {processor.py:163} INFO - Started process (PID=885) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:37,791] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:37,795] {logging_mixin.py:109} INFO - [2022-02-07 17:29:37,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:37,810] {logging_mixin.py:109} INFO - [2022-02-07 17:29:37,808] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",)
                                                                                             ^
SyntaxError: invalid syntax
[2022-02-07 17:29:37,843] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:37,868] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.087 seconds
[2022-02-07 17:29:40,968] {processor.py:163} INFO - Started process (PID=888) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:40,976] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:40,985] {logging_mixin.py:109} INFO - [2022-02-07 17:29:40,984] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:41,021] {logging_mixin.py:109} INFO - [2022-02-07 17:29:41,019] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",de)
                                                                                               ^
SyntaxError: invalid syntax
[2022-02-07 17:29:41,078] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:41,103] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.156 seconds
[2022-02-07 17:29:43,270] {processor.py:163} INFO - Started process (PID=891) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:43,272] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:43,277] {logging_mixin.py:109} INFO - [2022-02-07 17:29:43,277] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:43,290] {logging_mixin.py:109} INFO - [2022-02-07 17:29:43,288] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:29:43,324] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:43,344] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.080 seconds
[2022-02-07 17:29:46,652] {processor.py:163} INFO - Started process (PID=909) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:46,665] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:46,667] {logging_mixin.py:109} INFO - [2022-02-07 17:29:46,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:46,684] {logging_mixin.py:109} INFO - [2022-02-07 17:29:46,682] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:29:46,728] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:46,758] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.112 seconds
[2022-02-07 17:29:50,793] {processor.py:163} INFO - Started process (PID=918) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:50,796] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:50,798] {logging_mixin.py:109} INFO - [2022-02-07 17:29:50,797] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:50,815] {logging_mixin.py:109} INFO - [2022-02-07 17:29:50,814] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:29:50,852] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:50,872] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.085 seconds
[2022-02-07 17:29:53,060] {processor.py:163} INFO - Started process (PID=920) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:53,062] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:53,066] {logging_mixin.py:109} INFO - [2022-02-07 17:29:53,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:53,082] {logging_mixin.py:109} INFO - [2022-02-07 17:29:53,080] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:29:53,112] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:53,126] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.070 seconds
[2022-02-07 17:29:57,266] {processor.py:163} INFO - Started process (PID=923) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:57,270] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:29:57,273] {logging_mixin.py:109} INFO - [2022-02-07 17:29:57,273] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:57,287] {logging_mixin.py:109} INFO - [2022-02-07 17:29:57,286] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:29:57,318] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:29:57,334] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.072 seconds
[2022-02-07 17:30:00,889] {processor.py:163} INFO - Started process (PID=937) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:00,901] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:00,909] {logging_mixin.py:109} INFO - [2022-02-07 17:30:00,906] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:00,961] {logging_mixin.py:109} INFO - [2022-02-07 17:30:00,953] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=)
                                                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:30:01,031] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:01,063] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.191 seconds
[2022-02-07 17:30:03,464] {processor.py:163} INFO - Started process (PID=940) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:03,474] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:03,482] {logging_mixin.py:109} INFO - [2022-02-07 17:30:03,480] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:03,513] {logging_mixin.py:109} INFO - [2022-02-07 17:30:03,509] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=de)
                                                                                                            ^
SyntaxError: invalid syntax
[2022-02-07 17:30:03,568] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:03,587] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.138 seconds
[2022-02-07 17:30:08,187] {processor.py:163} INFO - Started process (PID=945) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:08,190] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:08,192] {logging_mixin.py:109} INFO - [2022-02-07 17:30:08,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:08,204] {logging_mixin.py:109} INFO - [2022-02-07 17:30:08,203] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=defa)
                                                                                                              ^
SyntaxError: invalid syntax
[2022-02-07 17:30:08,238] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:08,259] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.078 seconds
[2022-02-07 17:30:11,365] {processor.py:163} INFO - Started process (PID=948) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:11,370] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:11,373] {logging_mixin.py:109} INFO - [2022-02-07 17:30:11,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:11,394] {logging_mixin.py:109} INFO - [2022-02-07 17:30:11,391] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default)
                                                                                                                 ^
SyntaxError: invalid syntax
[2022-02-07 17:30:11,448] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:11,472] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.113 seconds
[2022-02-07 17:30:12,518] {processor.py:163} INFO - Started process (PID=950) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:12,520] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:12,522] {logging_mixin.py:109} INFO - [2022-02-07 17:30:12,522] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:12,535] {logging_mixin.py:109} INFO - [2022-02-07 17:30:12,534] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 6
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)
                                                                                                                      ^
SyntaxError: invalid syntax
[2022-02-07 17:30:12,571] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:12,591] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.081 seconds
[2022-02-07 17:30:27,995] {processor.py:163} INFO - Started process (PID=980) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:27,998] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:28,001] {logging_mixin.py:109} INFO - [2022-02-07 17:30:28,001] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:28,015] {logging_mixin.py:109} INFO - [2022-02-07 17:30:28,014] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-02-07 17:30:28,058] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:28,081] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.094 seconds
[2022-02-07 17:30:31,905] {processor.py:163} INFO - Started process (PID=997) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:31,909] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:30:31,924] {logging_mixin.py:109} INFO - [2022-02-07 17:30:31,924] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:31,946] {logging_mixin.py:109} INFO - [2022-02-07 17:30:31,943] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-02-07 17:30:31,979] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:30:32,002] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.110 seconds
[2022-02-07 17:31:02,132] {processor.py:163} INFO - Started process (PID=1051) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:02,134] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:02,136] {logging_mixin.py:109} INFO - [2022-02-07 17:31:02,135] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:02,148] {logging_mixin.py:109} INFO - [2022-02-07 17:31:02,146] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-02-07 17:31:02,180] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:02,196] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.068 seconds
[2022-02-07 17:31:24,023] {processor.py:163} INFO - Started process (PID=1088) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:24,027] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:24,029] {logging_mixin.py:109} INFO - [2022-02-07 17:31:24,028] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:24,043] {logging_mixin.py:109} INFO - [2022-02-07 17:31:24,041] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-02-07 17:31:24,075] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:24,097] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.080 seconds
[2022-02-07 17:31:29,423] {processor.py:163} INFO - Started process (PID=1101) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:29,425] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:29,427] {logging_mixin.py:109} INFO - [2022-02-07 17:31:29,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:29,455] {logging_mixin.py:109} INFO - [2022-02-07 17:31:29,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7, in <module>
    test
NameError: name 'test' is not defined
[2022-02-07 17:31:29,481] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:29,494] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.075 seconds
[2022-02-07 17:31:33,160] {processor.py:163} INFO - Started process (PID=1106) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:33,164] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:33,166] {logging_mixin.py:109} INFO - [2022-02-07 17:31:33,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:33,198] {logging_mixin.py:109} INFO - [2022-02-07 17:31:33,193] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7, in <module>
    test_function
NameError: name 'test_function' is not defined
[2022-02-07 17:31:33,225] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:33,241] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.086 seconds
[2022-02-07 17:31:34,179] {processor.py:163} INFO - Started process (PID=1107) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:34,182] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:34,188] {logging_mixin.py:109} INFO - [2022-02-07 17:31:34,188] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:34,210] {logging_mixin.py:109} INFO - [2022-02-07 17:31:34,209] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 7
    test_function=
                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:34,257] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:34,289] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.119 seconds
[2022-02-07 17:31:39,894] {processor.py:163} INFO - Started process (PID=1123) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:39,898] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:39,901] {logging_mixin.py:109} INFO - [2022-02-07 17:31:39,901] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:39,919] {logging_mixin.py:109} INFO - [2022-02-07 17:31:39,916] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2022-02-07 17:31:39,988] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:40,008] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.131 seconds
[2022-02-07 17:31:43,143] {processor.py:163} INFO - Started process (PID=1126) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:43,147] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:43,150] {logging_mixin.py:109} INFO - [2022-02-07 17:31:43,150] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:43,164] {logging_mixin.py:109} INFO - [2022-02-07 17:31:43,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 3
    from air
           ^
SyntaxError: invalid syntax
[2022-02-07 17:31:43,194] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:43,210] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.073 seconds
[2022-02-07 17:31:45,385] {processor.py:163} INFO - Started process (PID=1129) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:45,400] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:45,403] {logging_mixin.py:109} INFO - [2022-02-07 17:31:45,403] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:45,416] {logging_mixin.py:109} INFO - [2022-02-07 17:31:45,415] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 3
    from airflow.op
                  ^
SyntaxError: invalid syntax
[2022-02-07 17:31:45,467] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:45,483] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.108 seconds
[2022-02-07 17:31:47,649] {processor.py:163} INFO - Started process (PID=1133) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:47,652] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:47,654] {logging_mixin.py:109} INFO - [2022-02-07 17:31:47,654] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:47,670] {logging_mixin.py:109} INFO - [2022-02-07 17:31:47,669] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 3
    from airflow.operators.pyt
                             ^
SyntaxError: invalid syntax
[2022-02-07 17:31:47,719] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:47,741] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.097 seconds
[2022-02-07 17:31:51,902] {processor.py:163} INFO - Started process (PID=1156) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:51,904] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:51,907] {logging_mixin.py:109} INFO - [2022-02-07 17:31:51,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:51,934] {logging_mixin.py:109} INFO - [2022-02-07 17:31:51,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 3
    from airflow.operators.python_operator import
                                                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:51,997] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:52,026] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.129 seconds
[2022-02-07 17:31:54,137] {processor.py:163} INFO - Started process (PID=1159) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:54,139] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:54,141] {logging_mixin.py:109} INFO - [2022-02-07 17:31:54,141] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:54,154] {logging_mixin.py:109} INFO - [2022-02-07 17:31:54,153] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    test_function=
                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:54,193] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:54,213] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.081 seconds
[2022-02-07 17:31:55,260] {processor.py:163} INFO - Started process (PID=1161) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:55,262] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:55,265] {logging_mixin.py:109} INFO - [2022-02-07 17:31:55,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:55,284] {logging_mixin.py:109} INFO - [2022-02-07 17:31:55,282] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    test_function=
                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:55,323] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:55,347] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.094 seconds
[2022-02-07 17:31:56,390] {processor.py:163} INFO - Started process (PID=1162) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:56,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:56,395] {logging_mixin.py:109} INFO - [2022-02-07 17:31:56,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:56,412] {logging_mixin.py:109} INFO - [2022-02-07 17:31:56,410] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    test_function=
                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:56,452] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:56,474] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.091 seconds
[2022-02-07 17:31:59,636] {processor.py:163} INFO - Started process (PID=1165) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:59,639] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:31:59,642] {logging_mixin.py:109} INFO - [2022-02-07 17:31:59,642] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:59,661] {logging_mixin.py:109} INFO - [2022-02-07 17:31:59,658] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    test_function=
                 ^
SyntaxError: invalid syntax
[2022-02-07 17:31:59,704] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:31:59,730] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.100 seconds
[2022-02-07 17:32:08,670] {processor.py:163} INFO - Started process (PID=1184) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:08,672] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:08,675] {logging_mixin.py:109} INFO - [2022-02-07 17:32:08,674] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:08,706] {logging_mixin.py:109} INFO - [2022-02-07 17:32:08,704] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8, in <module>
    test_function=aPyt
NameError: name 'aPyt' is not defined
[2022-02-07 17:32:08,733] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:08,746] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.081 seconds
[2022-02-07 17:32:11,377] {processor.py:163} INFO - Started process (PID=1187) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:11,382] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:11,387] {logging_mixin.py:109} INFO - [2022-02-07 17:32:11,385] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:11,459] {logging_mixin.py:109} INFO - [2022-02-07 17:32:11,438] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8, in <module>
    test_function=a
NameError: name 'a' is not defined
[2022-02-07 17:32:11,512] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:11,531] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.160 seconds
[2022-02-07 17:32:14,820] {processor.py:163} INFO - Started process (PID=1191) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:14,823] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:14,827] {logging_mixin.py:109} INFO - [2022-02-07 17:32:14,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:14,875] {logging_mixin.py:109} INFO - [2022-02-07 17:32:14,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8, in <module>
    test_function=Python
NameError: name 'Python' is not defined
[2022-02-07 17:32:14,912] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:14,930] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.119 seconds
[2022-02-07 17:32:16,921] {processor.py:163} INFO - Started process (PID=1192) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:16,923] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:16,925] {logging_mixin.py:109} INFO - [2022-02-07 17:32:16,925] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:17,044] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:19,456] {logging_mixin.py:109} INFO - [2022-02-07 17:32:19,456] {manager.py:496} INFO - Created Permission View: can read on DAG:test_workflow
[2022-02-07 17:32:19,476] {logging_mixin.py:109} INFO - [2022-02-07 17:32:19,475] {manager.py:496} INFO - Created Permission View: can edit on DAG:test_workflow
[2022-02-07 17:32:19,477] {logging_mixin.py:109} INFO - [2022-02-07 17:32:19,477] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:32:19,489] {logging_mixin.py:109} INFO - [2022-02-07 17:32:19,488] {dag.py:2415} INFO - Creating ORM DAG for test_workflow
[2022-02-07 17:32:19,508] {logging_mixin.py:109} INFO - [2022-02-07 17:32:19,508] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:32:19,529] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 2.611 seconds
[2022-02-07 17:32:20,843] {processor.py:163} INFO - Started process (PID=1214) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:20,851] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:20,855] {logging_mixin.py:109} INFO - [2022-02-07 17:32:20,855] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:20,913] {logging_mixin.py:109} INFO - [2022-02-07 17:32:20,907] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8, in <module>
    test_function=PythonOperator()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:20,949] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:20,951] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:20,991] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.176 seconds
[2022-02-07 17:32:22,854] {processor.py:163} INFO - Started process (PID=1221) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:22,859] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:22,863] {logging_mixin.py:109} INFO - [2022-02-07 17:32:22,863] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:22,906] {logging_mixin.py:109} INFO - [2022-02-07 17:32:22,900] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8, in <module>
    test_function=PythonOperator(
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:22,964] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:22,999] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.149 seconds
[2022-02-07 17:32:30,982] {processor.py:163} INFO - Started process (PID=1227) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:30,987] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:30,989] {logging_mixin.py:109} INFO - [2022-02-07 17:32:30,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:31,025] {logging_mixin.py:109} INFO - [2022-02-07 17:32:31,021] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 9, in <module>
    task_id=""
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:31,065] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:31,086] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.109 seconds
[2022-02-07 17:32:35,796] {processor.py:163} INFO - Started process (PID=1242) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:35,798] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:35,800] {logging_mixin.py:109} INFO - [2022-02-07 17:32:35,800] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:35,832] {logging_mixin.py:109} INFO - [2022-02-07 17:32:35,827] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 9, in <module>
    task_id="test"
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:35,865] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:35,893] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.106 seconds
[2022-02-07 17:32:41,819] {processor.py:163} INFO - Started process (PID=1249) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:41,822] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:41,825] {logging_mixin.py:109} INFO - [2022-02-07 17:32:41,825] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:41,860] {logging_mixin.py:109} INFO - [2022-02-07 17:32:41,857] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 9, in <module>
    task_id="test_function"
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:41,892] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:41,905] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.090 seconds
[2022-02-07 17:32:43,985] {processor.py:163} INFO - Started process (PID=1251) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:43,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:43,991] {logging_mixin.py:109} INFO - [2022-02-07 17:32:43,991] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:44,037] {logging_mixin.py:109} INFO - [2022-02-07 17:32:44,032] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 9, in <module>
    task_id="test_function",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:44,078] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:44,096] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.116 seconds
[2022-02-07 17:32:49,400] {processor.py:163} INFO - Started process (PID=1267) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:49,408] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:49,412] {logging_mixin.py:109} INFO - [2022-02-07 17:32:49,412] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:49,459] {logging_mixin.py:109} INFO - [2022-02-07 17:32:49,454] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 9, in <module>
    task_id="test_function",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-02-07 17:32:49,490] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:49,504] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.118 seconds
[2022-02-07 17:32:54,747] {processor.py:163} INFO - Started process (PID=1280) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:54,752] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:54,756] {logging_mixin.py:109} INFO - [2022-02-07 17:32:54,755] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:54,784] {logging_mixin.py:109} INFO - [2022-02-07 17:32:54,783] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    pyt
    ^
SyntaxError: positional argument follows keyword argument
[2022-02-07 17:32:54,833] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:54,856] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.125 seconds
[2022-02-07 17:32:55,910] {processor.py:163} INFO - Started process (PID=1282) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:55,913] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:32:55,915] {logging_mixin.py:109} INFO - [2022-02-07 17:32:55,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:55,931] {logging_mixin.py:109} INFO - [2022-02-07 17:32:55,929] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 11
    )
    ^
SyntaxError: invalid syntax
[2022-02-07 17:32:55,965] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:32:55,982] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.077 seconds
[2022-02-07 17:33:07,580] {processor.py:163} INFO - Started process (PID=1302) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:07,582] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:07,584] {logging_mixin.py:109} INFO - [2022-02-07 17:33:07,584] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:07,598] {logging_mixin.py:109} INFO - [2022-02-07 17:33:07,597] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    def test_function
                    ^
SyntaxError: invalid syntax
[2022-02-07 17:33:07,623] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:07,655] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.079 seconds
[2022-02-07 17:33:09,709] {processor.py:163} INFO - Started process (PID=1304) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:09,713] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:09,715] {logging_mixin.py:109} INFO - [2022-02-07 17:33:09,715] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:09,736] {logging_mixin.py:109} INFO - [2022-02-07 17:33:09,734] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 8
    def test_function()
                      ^
SyntaxError: invalid syntax
[2022-02-07 17:33:09,774] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:09,796] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.096 seconds
[2022-02-07 17:33:12,092] {processor.py:163} INFO - Started process (PID=1308) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:12,095] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:12,097] {logging_mixin.py:109} INFO - [2022-02-07 17:33:12,096] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:12,110] {logging_mixin.py:109} INFO - [2022-02-07 17:33:12,108] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)as dag:
       ^
IndentationError: expected an indented block
[2022-02-07 17:33:12,145] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:12,176] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.089 seconds
[2022-02-07 17:33:22,740] {processor.py:163} INFO - Started process (PID=1331) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:22,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:22,747] {logging_mixin.py:109} INFO - [2022-02-07 17:33:22,746] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:22,768] {logging_mixin.py:109} INFO - [2022-02-07 17:33:22,764] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 11
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)as dag:
       ^
IndentationError: expected an indented block
[2022-02-07 17:33:22,817] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:22,844] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.114 seconds
[2022-02-07 17:33:27,292] {processor.py:163} INFO - Started process (PID=1337) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:27,297] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:27,301] {logging_mixin.py:109} INFO - [2022-02-07 17:33:27,300] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:27,334] {logging_mixin.py:109} INFO - [2022-02-07 17:33:27,331] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 12
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)as dag:
       ^
IndentationError: expected an indented block
[2022-02-07 17:33:27,407] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:27,433] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.151 seconds
[2022-02-07 17:33:30,007] {processor.py:163} INFO - Started process (PID=1350) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:30,013] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:30,015] {logging_mixin.py:109} INFO - [2022-02-07 17:33:30,015] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:30,030] {logging_mixin.py:109} INFO - [2022-02-07 17:33:30,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 13
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)as dag:
       ^
IndentationError: expected an indented block
[2022-02-07 17:33:30,068] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:30,106] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.104 seconds
[2022-02-07 17:33:36,964] {processor.py:163} INFO - Started process (PID=1355) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:36,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:36,974] {logging_mixin.py:109} INFO - [2022-02-07 17:33:36,974] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:36,994] {logging_mixin.py:109} INFO - [2022-02-07 17:33:36,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("")
                   ^
SyntaxError: invalid syntax
[2022-02-07 17:33:37,051] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:37,080] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.124 seconds
[2022-02-07 17:33:54,588] {processor.py:163} INFO - Started process (PID=1390) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:54,592] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:54,595] {logging_mixin.py:109} INFO - [2022-02-07 17:33:54,595] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:54,610] {logging_mixin.py:109} INFO - [2022-02-07 17:33:54,608] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files")
                                            ^
SyntaxError: invalid syntax
[2022-02-07 17:33:54,645] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:54,667] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.082 seconds
[2022-02-07 17:33:56,792] {processor.py:163} INFO - Started process (PID=1402) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:56,795] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:33:56,798] {logging_mixin.py:109} INFO - [2022-02-07 17:33:56,798] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:56,821] {logging_mixin.py:109} INFO - [2022-02-07 17:33:56,818] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files/")
                                             ^
SyntaxError: invalid syntax
[2022-02-07 17:33:56,884] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:33:56,926] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.142 seconds
[2022-02-07 17:34:00,300] {processor.py:163} INFO - Started process (PID=1406) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:00,304] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:00,307] {logging_mixin.py:109} INFO - [2022-02-07 17:34:00,307] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:00,326] {logging_mixin.py:109} INFO - [2022-02-07 17:34:00,324] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files/test.txt")
                                                     ^
SyntaxError: invalid syntax
[2022-02-07 17:34:00,368] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:00,393] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.101 seconds
[2022-02-07 17:34:03,332] {processor.py:163} INFO - Started process (PID=1407) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:03,336] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:03,339] {logging_mixin.py:109} INFO - [2022-02-07 17:34:03,338] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:03,353] {logging_mixin.py:109} INFO - [2022-02-07 17:34:03,351] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files/test.txt",:'w')
                                                      ^
SyntaxError: invalid syntax
[2022-02-07 17:34:03,390] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:03,408] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.087 seconds
[2022-02-07 17:34:06,432] {processor.py:163} INFO - Started process (PID=1412) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:06,440] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:06,447] {logging_mixin.py:109} INFO - [2022-02-07 17:34:06,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:06,485] {logging_mixin.py:109} INFO - [2022-02-07 17:34:06,481] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files/test.txt","w")
                                                         ^
SyntaxError: invalid syntax
[2022-02-07 17:34:06,553] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:06,587] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.163 seconds
[2022-02-07 17:34:13,469] {processor.py:163} INFO - Started process (PID=1429) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:13,475] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:13,480] {logging_mixin.py:109} INFO - [2022-02-07 17:34:13,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:13,518] {logging_mixin.py:109} INFO - [2022-02-07 17:34:13,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 10
    with io.open("/opt/airflow/output_files/test.txt","w",encoding="utf-8")
                                                                          ^
SyntaxError: invalid syntax
[2022-02-07 17:34:13,585] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:13,621] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.159 seconds
[2022-02-07 17:34:17,310] {processor.py:163} INFO - Started process (PID=1434) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:17,312] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:17,317] {logging_mixin.py:109} INFO - [2022-02-07 17:34:17,316] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:17,330] {logging_mixin.py:109} INFO - [2022-02-07 17:34:17,329] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 14
    with DAG(dag_id="test_workflow",start_date=datetime(2022,2,7),schedule_interval="@daily",default_args=default_args)as dag:
                                                                                                                             ^
IndentationError: expected an indented block
[2022-02-07 17:34:17,365] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:17,384] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.079 seconds
[2022-02-07 17:34:22,703] {processor.py:163} INFO - Started process (PID=1444) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:22,708] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:22,713] {logging_mixin.py:109} INFO - [2022-02-07 17:34:22,712] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:22,731] {logging_mixin.py:109} INFO - [2022-02-07 17:34:22,729] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 18
    )
    ^
SyntaxError: invalid syntax
[2022-02-07 17:34:22,777] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:22,805] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.112 seconds
[2022-02-07 17:34:29,574] {processor.py:163} INFO - Started process (PID=1463) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:29,577] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:29,578] {logging_mixin.py:109} INFO - [2022-02-07 17:34:29,578] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:29,591] {logging_mixin.py:109} INFO - [2022-02-07 17:34:29,589] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 18
    )
    ^
SyntaxError: invalid syntax
[2022-02-07 17:34:29,617] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:29,635] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.066 seconds
[2022-02-07 17:34:34,694] {processor.py:163} INFO - Started process (PID=1465) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:34,698] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:34,701] {logging_mixin.py:109} INFO - [2022-02-07 17:34:34,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:34,723] {logging_mixin.py:109} INFO - [2022-02-07 17:34:34,721] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 19
    )
    ^
SyntaxError: invalid syntax
[2022-02-07 17:34:34,776] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:34,812] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.126 seconds
[2022-02-07 17:34:39,724] {processor.py:163} INFO - Started process (PID=1480) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:39,728] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:39,732] {logging_mixin.py:109} INFO - [2022-02-07 17:34:39,732] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:39,785] {logging_mixin.py:109} INFO - [2022-02-07 17:34:39,780] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/test_workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_workflow.py", line 18, in <module>
    python_callable=tes
NameError: name 'tes' is not defined
[2022-02-07 17:34:39,858] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:39,882] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.168 seconds
[2022-02-07 17:34:41,569] {processor.py:163} INFO - Started process (PID=1484) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:41,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:34:41,577] {logging_mixin.py:109} INFO - [2022-02-07 17:34:41,577] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:41,688] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:34:42,044] {logging_mixin.py:109} INFO - [2022-02-07 17:34:42,043] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:34:42,090] {logging_mixin.py:109} INFO - [2022-02-07 17:34:42,089] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:34:42,124] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.562 seconds
[2022-02-07 17:35:12,620] {processor.py:163} INFO - Started process (PID=1537) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:12,623] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:35:12,625] {logging_mixin.py:109} INFO - [2022-02-07 17:35:12,625] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:12,672] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:12,685] {logging_mixin.py:109} INFO - [2022-02-07 17:35:12,685] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:35:12,707] {logging_mixin.py:109} INFO - [2022-02-07 17:35:12,707] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:35:12,721] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.107 seconds
[2022-02-07 17:35:43,434] {processor.py:163} INFO - Started process (PID=1591) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:43,437] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:35:43,439] {logging_mixin.py:109} INFO - [2022-02-07 17:35:43,439] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:43,507] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:35:43,533] {logging_mixin.py:109} INFO - [2022-02-07 17:35:43,533] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:35:43,574] {logging_mixin.py:109} INFO - [2022-02-07 17:35:43,574] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:35:43,741] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.313 seconds
[2022-02-07 17:36:13,931] {processor.py:163} INFO - Started process (PID=1643) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:13,934] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:36:13,936] {logging_mixin.py:109} INFO - [2022-02-07 17:36:13,936] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:14,000] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:14,028] {logging_mixin.py:109} INFO - [2022-02-07 17:36:14,028] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:36:14,185] {logging_mixin.py:109} INFO - [2022-02-07 17:36:14,185] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:36:14,201] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.275 seconds
[2022-02-07 17:36:44,921] {processor.py:163} INFO - Started process (PID=1696) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:44,927] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:36:44,931] {logging_mixin.py:109} INFO - [2022-02-07 17:36:44,930] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:45,005] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:36:45,020] {logging_mixin.py:109} INFO - [2022-02-07 17:36:45,020] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:36:45,150] {logging_mixin.py:109} INFO - [2022-02-07 17:36:45,150] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:36:45,165] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.250 seconds
[2022-02-07 17:37:15,704] {processor.py:163} INFO - Started process (PID=1759) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:15,721] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:37:15,732] {logging_mixin.py:109} INFO - [2022-02-07 17:37:15,731] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:15,893] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:15,929] {logging_mixin.py:109} INFO - [2022-02-07 17:37:15,929] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:37:16,304] {logging_mixin.py:109} INFO - [2022-02-07 17:37:16,303] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:37:16,335] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.639 seconds
[2022-02-07 17:37:46,685] {processor.py:163} INFO - Started process (PID=1813) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:46,691] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:37:46,694] {logging_mixin.py:109} INFO - [2022-02-07 17:37:46,693] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:46,787] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:37:46,921] {logging_mixin.py:109} INFO - [2022-02-07 17:37:46,921] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:37:46,960] {logging_mixin.py:109} INFO - [2022-02-07 17:37:46,959] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:37:46,980] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.300 seconds
[2022-02-07 17:38:17,203] {processor.py:163} INFO - Started process (PID=1866) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:17,206] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:38:17,208] {logging_mixin.py:109} INFO - [2022-02-07 17:38:17,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:17,377] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:17,392] {logging_mixin.py:109} INFO - [2022-02-07 17:38:17,392] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:38:17,417] {logging_mixin.py:109} INFO - [2022-02-07 17:38:17,416] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:38:17,430] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.232 seconds
[2022-02-07 17:38:47,873] {processor.py:163} INFO - Started process (PID=1920) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:47,875] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:38:47,877] {logging_mixin.py:109} INFO - [2022-02-07 17:38:47,877] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:48,025] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:38:48,037] {logging_mixin.py:109} INFO - [2022-02-07 17:38:48,036] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:38:48,054] {logging_mixin.py:109} INFO - [2022-02-07 17:38:48,054] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:38:48,069] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.199 seconds
[2022-02-07 17:39:18,644] {processor.py:163} INFO - Started process (PID=1970) to work on /opt/airflow/dags/test_workflow.py
[2022-02-07 17:39:18,648] {processor.py:642} INFO - Processing file /opt/airflow/dags/test_workflow.py for tasks to queue
[2022-02-07 17:39:18,650] {logging_mixin.py:109} INFO - [2022-02-07 17:39:18,649] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:39:18,812] {processor.py:654} INFO - DAG(s) dict_keys(['test_workflow']) retrieved from /opt/airflow/dags/test_workflow.py
[2022-02-07 17:39:18,831] {logging_mixin.py:109} INFO - [2022-02-07 17:39:18,830] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-07 17:39:18,854] {logging_mixin.py:109} INFO - [2022-02-07 17:39:18,854] {dag.py:2935} INFO - Setting next_dagrun for test_workflow to 2022-02-07T00:00:00+00:00
[2022-02-07 17:39:18,868] {processor.py:171} INFO - Processing /opt/airflow/dags/test_workflow.py took 0.228 seconds
