[2022-02-14 11:01:28,418] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-13T00:00:00+00:00 [queued]>
[2022-02-14 11:01:29,232] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_workflow.test_function scheduled__2022-02-13T00:00:00+00:00 [queued]>
[2022-02-14 11:01:29,234] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-14 11:01:29,240] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-14 11:01:29,244] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-14 11:01:29,730] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): test_function> on 2022-02-13 00:00:00+00:00
[2022-02-14 11:01:30,094] {standard_task_runner.py:52} INFO - Started process 131 to run task
[2022-02-14 11:01:30,346] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'test_function', 'scheduled__2022-02-13T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/test_workflow.py', '--cfg-path', '/tmp/tmpq03ef1ui', '--error-file', '/tmp/tmp6mo4vw8h']
[2022-02-14 11:01:30,433] {standard_task_runner.py:77} INFO - Job 282: Subtask test_function
[2022-02-14 11:01:32,864] {logging_mixin.py:109} INFO - Running <TaskInstance: test_workflow.test_function scheduled__2022-02-13T00:00:00+00:00 [running]> on host 809d0f9062f6
[2022-02-14 11:01:34,382] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_workflow
AIRFLOW_CTX_TASK_ID=test_function
AIRFLOW_CTX_EXECUTION_DATE=2022-02-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-13T00:00:00+00:00
[2022-02-14 11:01:34,455] {python.py:175} INFO - Done. Returned value was: None
[2022-02-14 11:01:35,855] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=test_workflow, task_id=test_function, execution_date=20220213T000000, start_date=20220214T110128, end_date=20220214T110135
[2022-02-14 11:01:36,492] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-02-14 11:01:36,554] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 131. PIDs of all processes in the group: [131]
[2022-02-14 11:01:36,580] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 131
[2022-02-14 11:01:36,614] {process_utils.py:70} INFO - Process psutil.Process(pid=131, status='terminated', exitcode=0, started='11:01:29') (131) terminated with exit code 0
